use hyprland_config::{
    comment::{Comment, MultiLineComment, OneLineComment},
    util::Parse,
};

#[test]
fn test_comment_parser() {
    let input = "# This is a comment";
    let rest_comment = Comment::parse(input);
    assert_eq!(
        rest_comment,
        Ok(("", Comment::OneLine(OneLineComment(input.to_string()))))
    );

    let input = r"
########################################################################################
AUTOGENERATED HYPR CONFIG.
PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
########################################################################################
    "
    .trim();
    let rest_comment = Comment::parse(input);
    assert_eq!(
        rest_comment,
        Ok(("", Comment::MultiLine(MultiLineComment(input.to_string()))))
    );
}
